### ISSUE TITLE
FL11_HW13 issues with files in index.html

### ISSUE THREAD

**Issue by var-bin** [AnToX1c/FL-11#1]
Hi Anton,

I try to check your [FL11_HW13](https://github.com/AnToX1c/FL-11/tree/master/FL11_HW13/homework). Unfortunately, `index.html` doesn't work at all. Take a peek to screenshot.
As I see, the main problem is CORS. One of the solutions is to use a local server which is not suitable for me. Try to replace local links for third-party libs to CDN links

![AnToX1c-FL11_HW13](https://user-images.githubusercontent.com/3194163/63575718-6b259400-c593-11e9-95f3-9cef372e1433.png)

**Comment by AnToX1c** [comment]
Hi, Vitalii!

I understand your problem, but i think using local server is provided by homework.
Please consider my arguments below.
We deal with not only third-party libs. We have our own 'less' styles.
Anyway, you can not avoid to use local server while check next homework 'FL11_HW14' or FL11_HW13 others guys!
One of the solutions could be: if you use VSCode, it has the plugin 'http-server'. Or if you use WebStorm it's possible to run local server by default.

**Comment by var-bin** [comment]
Hi, @AnToX1c!

Thank you for your input. I was able to manage this issue by my self. But still, it looks weird that I need to run local server for checking HTML, CSS ;-)

P.S. I understand, that this is not your own decision
